language: node_js
sudo: required 
services: 
  - docker
branches:
  only:
    - main
cache:
  directories:
    - travis-build
before_install:
  # Clean install on any new build
  - npm run clean
jobs:
  include:
    - stage: lint and jest
      script:
        - npm run lint
        - npm run jest
stages:
  - lint and jest
